start-process -FilePath "C:\Program Files\Internet Explorer\iexplore.exe" -ArgumentList "http://gblonbm02/MR/default.aspx"
start-process -FilePath "C:\Program Files\Internet Explorer\iexplore.exe" -ArgumentList "http://gblonbm02/default.aspx"
start-process -FilePath "C:\Program Files\Internet Explorer\iexplore.exe" -ArgumentList "http://gblonbm02/Induction/Forms/AllItems.aspx"
start-process -FilePath "C:\Program Files\Internet Explorer\iexplore.exe" -ArgumentList "http://gblonbm02/Documents/Forms/AllItems.aspx"
start-process -FilePath "C:\Program Files\Internet Explorer\iexplore.exe" -ArgumentList "http://gblonbm02/PhoneNumbers/default.aspx"